export const TagActions = {
  SAVE_TAG_AS_FRONT:'SAVE_TAG_AS_FRONT',
  SAVE_TAG_AS_FRONT_SUCCESS:'SAVE_TAG_AS_FRONT_SUCCESS',
  DELETE_TAG:'DELETE_TAG',
  DELETE_TAG_SUCCESS:'DELETE_TAG_SUCCESS',
  ADD_TAG:'ADD_TAG',
  ADD_TAG_SUCCESS:'ADD_TAG_SUCCESS',
  GET_TAG:'GET_TAG',
  GET_TAG_SUCCESS:'GET_TAG_SUCCESS'
}
