export const UserActions = {
  LOGIN:'LOGIN',
  LOGIN_SUCCESS:'LOGIN_SUCCESS',
  REGISTER:'REGISTER',
  REGISTER_SUCCESS:'REGISTER_SUCCESS',
  AUTH_CHECK:'AUTH_CHECK',
  AUTH_CHECK_SUCCESS:'AUTH_CHECK_SUCCESS',
  LOGOUT:'LOGOUT',
  LOGOUT_SUCCESS:'LOGOUT_SUCCESS',
  GET_ALL_USERS:'GET_ALL_USERS',
  GET_ALL_USERS_SUCCESS:'GET_ALL_USERS_SUCCESS',
  DELETE_USER:'DELETE_USER',
  DELETE_USER_SUCCESS:'DELETE_USER_SUCCESS',
  CHANGE_USER_TYPE:'CHANGE_USER_TYPE',
  CHANGE_USER_TYPE_SUCCESS:'CHANGE_USER_TYPE_SUCCESS',
  GITHUB_LOGIN:'GITHUB_LOGIN'
}
